stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-adoptopenjdk-11
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-patron-blocks:vega-modpatblk-41
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-wntj9:vega-helmcharts-mod-patron-blocks
          version: 1.1.0
          answers:
            image.repository: docker.dev.folio.org/mod-patron-blocks
            image.tag: vega-modpatblk-41
          targetNamespace: vega
          name: mod-patron-blocks
timeout: 60
notification: {}
